apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-nursery-to-elementary-school
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-nursery-to-elementary-school
  template:
    metadata:
      labels:
        app: spring-nursery-to-elementary-school
    spec:
      containers:
        - name: spring-nursery-to-elementary-school
          image: spring-nursery-to-elementary-school:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: spring-nursery-to-elementary-school-balancer
spec:
  selector:
    app: spring-nursery-to-elementary-school
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
